# Generated by Django 3.2.8 on 2021-10-28 17:39

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='email')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apellido_uno', models.CharField(default='', max_length=50)),
                ('apellido_dos', models.CharField(default='', max_length=50)),
                ('cedula', models.CharField(default='', max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(auto_now=True)),
                ('genero', models.CharField(default='', max_length=1)),
                ('fecha_ingreso', models.DateField(auto_now=True)),
                ('numero_empleado', models.IntegerField(default=1, unique=True)),
                ('cargo', models.CharField(default='', max_length=20)),
                ('jefe', models.IntegerField(default=100)),
                ('zona', models.CharField(default='', max_length=20)),
                ('municipio', models.CharField(default='', max_length=20)),
                ('departamento', models.CharField(default='', max_length=20)),
                ('ventas', models.IntegerField(default=100)),
                ('imagen', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('celular', models.CharField(default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
