# Generated by Django 3.2.8 on 2021-10-29 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211028_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
